openapi: 3.0.0
info:
  title: car_shop_service
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: cars
  - name: cars > filter
  - name: clients
  - name: clients > cars
  - name: clients > filter
  - name: clients > manager
  - name: employees
  - name: employees > filter
  - name: orders
  - name: orders > client
  - name: orders > filter
  - name: requests
  - name: requests > client
  - name: requests > filter
  - name: login
paths:
  /carshopservice/api/cars:
    get:
      tags:
        - cars
      summary: view all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - cars
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                brand: Toyota
                model: Camry
                year: 2018
                price: 20000
                condition: Used
                color: Red
                availability: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - cars
      summary: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                brand: Toyota
                model: Wolver
                year: 2022
                price: 30000
                condition: new
                color: blue
                availability: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/cars/100:
    delete:
      tags:
        - cars
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/clients/cars:
    get:
      tags:
        - clients > cars
      summary: view client's cars
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/clients/filter:
    get:
      tags:
        - clients > filter
      summary: filter_clients
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/clients/manager:
    get:
      tags:
        - clients > manager
      summary: manager_clients
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/clients:
    get:
      tags:
        - clients
      summary: view all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - clients
      summary: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: michaelj
                password: password123
                role: CLIENT
                name: Michael Johnson
                email: michaelj@outlook.com
                phone: '+1234567893'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - clients
      summary: udpate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: michaelj
                password: '456'
                role: CLIENT
                name: Loren Johnson
                email: loren@outlook.com
                phone: '+79853255532'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - clients
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/employee/filter:
    get:
      tags:
        - employees > filter
      summary: filter_employee
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/employee:
    get:
      tags:
        - employees
      summary: view all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - employees
      summary: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: michaelj
                password: password123
                role: MANAGER
                name: Michael Johnson
                email: michaelj@outlook.com
                phone: '+1234567893'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - employees
      summary: udpate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: michaelj
                password: '12'
                role: MANAGER
                name: Michael Jordano
                email: jordan@outlook.com
                phone: '+1234567893'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - employees
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/orders/client:
    get:
      tags:
        - orders > client
      summary: get_client_orders
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/orders/filter:
    get:
      tags:
        - requests > filter
      summary: filter requests
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/orders:
    get:
      tags:
        - orders
      summary: view all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - orders
      summary: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                car:
                  id: 1
                  brand: Toyota
                  model: Camry
                  year: 2018
                  price: 20000
                  condition: Used
                  color: White
                  availability: true
                client:
                  id: 2
                  username: cl
                  password: '123'
                  role: CLIENT
                  name: Jane Doe
                  email: janedoe@example.com
                  phone: '+1234567891'
                orderDate: 1690822800000
                status: PENDING
                type: BUYING
                note: First order
                manager:
                  id: 1
                  username: man
                  password: '123'
                  role: MANAGER
                  name: John Doe
                  email: johndoe@example.com
                  phone: '+1234567890'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - orders
      summary: udpate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 101
                car:
                  id: 2
                client:
                  id: 2
                orderDate: 1690822800000
                status: PENDING
                type: BUYING
                note: First order
                manager:
                  id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - requests
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/requests/client:
    get:
      tags:
        - requests > client
      summary: get_client_orders
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/api/requests:
    get:
      tags:
        - requests
      summary: view all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - requests
      summary: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                car:
                  id: 1
                client:
                  id: 2
                orderDate: 1690822800000
                status: PENDING
                type: SERVICE
                note: First order
                manager:
                  id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - requests
      summary: udpate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 102
                car:
                  id: 2
                client:
                  id: 2
                orderDate: 1690822800000
                status: PENDING
                type: SERVICE
                note: First order
                manager:
                  id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carshopservice/login:
    get:
      tags:
        - login
      summary: login in
      parameters:
        - name: login
          in: query
          schema:
            type: string
          example: cl
        - name: password
          in: query
          schema:
            type: string
          example: man
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}