version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_shop_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
